name: dan

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:8080"
    secrets:
      - postgres_password
      - postgres_username
    depends_on:
      - db

  db:
    image: postgres:16.3
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_username
    ports:
      - "5432:5432"
    secrets:
      - postgres_password
      - postgres_username

secrets:
  postgres_password:
    file: ./secrets/db_password.txt
  postgres_username:
    file: ./secrets/db_username.txt