spring:
  application:
    name:
      task-manager
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate
    open-in-view: false
  mvc:
    format:
      date: iso

server:
  error:
    whitelabel:
      enabled: false